### ISSUE TITLE
adlandirma

### ISSUE THREAD

**Issue by samirkarimov** [Yusif7/PragmatechFoundationProject#2]
https://github.com/Yusif7/PragmatechFoundationProject/blob/b1fb633958f1f2fa2829fe1125af785a1a908d6c/index.html#L16

iki ya da daha cox soz istifade olunan class ve id adlarinda ferqlendirme etmek lazimdir. navbarleft yerine navbar-left ya da navbar_left kimi adlandirma usulu daha duzgundur.

Research movzusu : html css naming conventions

**Comment by Yusif7** [comment]
Bu hefte sonu bu meseleni hell edecem.

**Comment by Yusif7** [comment]
Duzəliş olundu
