### ISSUE TITLE
SASS | Diqqet olunmali meqamlar

### ISSUE THREAD

**Issue by samirkarimov** [Yusif7/PragmatechFoundationProject#3]
- Ortaq class mentigi qurmamisan zennimce bu seni daha sonradan yoracaq
- Grid sisteminde container>row>col siralamasini daimi istifade etmek lazimdir. row>col ya da sadece col istifadesi duzgun yanasma deyil
- deyisenlerden az istifade etmisen. her hansi deyeri butun fayllarda search edib nece yerde istifade olundugunu analiz edebilersen eger 2 ya da daha cox yerde istifade olunubsa bunu variable halina getirmek ela olar
- ortaq class yaradmag ucun hint olaraq sass foreach istifadesi numunesine baxabilersen
```
@for $i from 1 through 4 {
    .p-#{$i} {
        padding: $spacing-1x*$i
    }
    .pt-#{$i} {
        padding-top: $spacing-1x*$i
    }
    .pb-#{$i} {
        padding-bottom: $spacing-1x*$i
    }
    .pl-#{$i} {
        padding-left: $spacing-1x*$i
    }
    .pr-#{$i} {
        padding-right: $spacing-1x*$i
    }
    .px-#{$i} {
        padding: 0px $spacing-1x*$i !important
    }
    .py-#{$i} {
        padding: $spacing-1x*$i 0px !important;
    }
}
```

- list ve foreach istifadesi
```
$align-list:flex-start,
flex-end,
center,
baseline,
stretch;
@each $item in $align-list {
    .align-#{$item} {
        align-items: $item;
    }
}
```

**Comment by Yusif7** [comment]
- Margin ve padding ucun ortaq klass sistemi yaradildi.
