### ISSUE TITLE
Javascript problemlerinin analizi

### ISSUE THREAD

**Issue by samirkarimov** [Yusif7/PragmatechFoundationProject#4]
Javascriptde etmek istediyin meseleleri geyd etsen ona gore pull reguest edebilerem

**Comment by Yusif7** [comment]
Her iki mesele template olan blog page ile elagedardi.
![Screenshot_2](https://user-images.githubusercontent.com/15730977/102555302-ed6a8d80-40df-11eb-9aa9-8c023bdfdbde.png)

1. Modal acildigi zaman, diger modallar arasi kecid ucun prev next arrow mentigini qurmaq isteyirem. Multiple modal mentigini qurmusam.Prev/Next buttonlarini modal daxilinde aktivlesdirmek ucun hansi mentigi izlemelyem.
2. Template blog inner pagede 3 fergli modal yaradilib ve modal acildigi zaman necenci oldugu qeyd olunur ex: 1of 3.Bu yanasmani array olaraq dusunurem ve hansi modalin acildiginin teyin etmek ucun  acilan modalin src == array elemntlerini for ile yoxlayim onu sonra cixardim ekrana dinamik hell deyil ama aglima basqa cozum gelmir.

**Comment by samirkarimov** [comment]
Hal hazirda activdirmi bu issue?

**Comment by Yusif7** [comment]
Ozum hell etmedim, hazir plugin istifade etdim.Aktiv deyil.
